"""AURELIS: Solve-Free Recurrent Memory with Residual-Certified Retrieval."""

from .archive import (
    Archive,
    archive_reference_read,
)
from .functional import (
    bounded_read,
    completed_read,
    compute_page_envelope,
    full_history_softmax,
    gated_delta_update,
    local_attention,
    pointwise_envelope,
    residual_certificate,
)
from .oracles import (
    ScalarOracle,
    ScalarStreamingOracle,
    TensorOracle,
    TensorStreamingOracle,
)
from .certificate import (
    compute_numerical_allowance,
    compute_outward_page_envelope,
    compute_outward_score_interval,
    evaluate_certified_bound,
    gamma,
    get_unit_roundoff,
    validate_intervals,
    validate_page_summary,
    validate_unread_cover,
)
from .comparators import (
    AccountingRecord,
    ComparatorResult,
    compute_composite_cost,
    execute_comparator,
)
from .policy import (
    CandidateState,
    RetrievalPolicy,
)
from .session import AurelisSession
from .streaming import (
    consume,
    create_snapshot,
    initial_state,
    occurrence_partition,
    read,
    restore_from_snapshot,
)
from .types import (
    ArchiveEntry,
    CertificateBound,
    DeltaState,
    MemoryProfile,
    PageDescriptor,
    ReadResult,
    ReadStatus,
    StateSnapshot,
)
from .workloads import (
    WorkloadInstance,
    generate_abrupt_drift_workload,
    generate_boundary_retrieval_workload,
    generate_delayed_disambiguation_workload,
    generate_diffuse_attention_workload,
    generate_large_value_outliers_workload,
    generate_metadata_dominant_workload,
    generate_multihop_query_workload,
    generate_near_collisions_workload,
    generate_random_incompressible_workload,
    generate_repeated_keys_workload,
    generate_structured_linear_workload,
)
from .ablations import (
    AblationRecord,
    run_delayed_vs_immediate_ablation,
    run_mass_correction_ablation,
    run_recurrence_dimension_ablation,
    run_residual_selection_ablation,
    run_summary_quality_ablation,
    run_transport_vs_local_ablation,
)

__all__ = [
    "AblationRecord",
    "AccountingRecord",
    "Archive",
    "ArchiveEntry",
    "AurelisSession",
    "CandidateState",
    "CertificateBound",
    "ComparatorResult",
    "DeltaState",
    "MemoryProfile",
    "PageDescriptor",
    "ReadResult",
    "ReadStatus",
    "RetrievalPolicy",
    "ScalarOracle",
    "ScalarStreamingOracle",
    "StateSnapshot",
    "TensorOracle",
    "TensorStreamingOracle",
    "WorkloadInstance",
    "archive_reference_read",
    "bounded_read",
    "completed_read",
    "compute_composite_cost",
    "compute_numerical_allowance",
    "compute_outward_page_envelope",
    "compute_outward_score_interval",
    "compute_page_envelope",
    "consume",
    "create_snapshot",
    "evaluate_certified_bound",
    "execute_comparator",
    "full_history_softmax",
    "gamma",
    "gated_delta_update",
    "generate_abrupt_drift_workload",
    "generate_boundary_retrieval_workload",
    "generate_delayed_disambiguation_workload",
    "generate_diffuse_attention_workload",
    "generate_large_value_outliers_workload",
    "generate_metadata_dominant_workload",
    "generate_multihop_query_workload",
    "generate_near_collisions_workload",
    "generate_random_incompressible_workload",
    "generate_repeated_keys_workload",
    "generate_structured_linear_workload",
    "get_unit_roundoff",
    "initial_state",
    "local_attention",
    "occurrence_partition",
    "pointwise_envelope",
    "read",
    "residual_certificate",
    "restore_from_snapshot",
    "run_delayed_vs_immediate_ablation",
    "run_mass_correction_ablation",
    "run_recurrence_dimension_ablation",
    "run_residual_selection_ablation",
    "run_summary_quality_ablation",
    "run_transport_vs_local_ablation",
    "validate_intervals",
    "validate_page_summary",
    "validate_unread_cover",
]
